### ISSUE TITLE
custom styled journal popout limit height after .15 update

### ISSUE THREAD

**Issue by nygaards** [League-of-Foundry-Developers/fvtt-module-popout#113]
after updating to 2.15 from 2.14 when I popout journals with custom styling (found using: season of ghost book 1) the bottom border is locked to a specific height. when opened in foundry rescaling works with no issue
running 11.315, pathfinder 2e 5.13.6
![image](https://github.com/League-of-Foundry-Developers/fvtt-module-popout/assets/64007321/5d7084ef-146c-4458-9975-4dfd51b86ae8)

**Comment by BadIdeasBureau** [comment]
I'm seeing the same thing on Lancer's pilot sheets. Chrome  121.0.6167.185 , Windows 10, Foundry v10,312 , Lancer v1.6.1

Toggling the bounding box option off fixes it, as expected (though for others here, note that that's a client setting so each affected player needs to do the thing).

Doesn't seem to be entirely consistent - had one player get it always on the pilot sheet and only occasionally on the mech sheet.

**Comment by Posnet** [comment]
I have made a new release that disabled the height adjustment for the bounding algo (the same behavior as before), until I can work out exactly what is going on (I think windows might be doing something different to mac and linux). Since most of the reason for that button was things buttons off the sides of sheets, I have yet to see one were the button was below as sheet.

**Comment by kristianserrano** [comment]
I had a similar thing happen on macOS with the latest Chrome with SWADE character sheets.

**Comment by Posnet** [comment]
@kristianserrano is it still happening with Popout! v2.15

**Comment by nygaards** [comment]
it has been fixed. sorry for not responding with it being fixed.
