### ISSUE TITLE
API enhancement - Replacing contents of a popped-out window

### ISSUE THREAD

**Issue by BadIdeasBureau** [League-of-Foundry-Developers/fvtt-module-popout#114]
For enabling some in-person play shenaningans, I want to have a second display which always shows the character sheet of the active combatant.

An ideal way to do this, if possible, would be to be able to have a popped-out window on that display, and be able to (via module code) swap which app is displayed in that window at will.

Is this something that would be potentially in scope? (or something already doable in a way I'm not smart enough to figure out!)

**Comment by Posnet** [comment]
This would add too much complexity to implement as a part of Popout!.
However I think you could achieve essentially what you are asking for if you, prior to combat, popout each participant (with new, window disabled) into their own tab.
Then shift select all the new tabs and drag them to a new window. 
Now when the character it clicked it should move to the tab of that character dynamically. 
This should be achievable programmatically by calling the `bringToTop` method of the character sheet application, since this is intercepted by Popout! and draws focus.
One caveat is that often programmatically drawing window/tab focus is often blocked by the browsers anti-popup features, so make sure you're calling the bringToTop function from inside a click handler, like the end turn button.
