### ISSUE TITLE
Request: Compatability with minimap module

### ISSUE THREAD

**Issue by SamF111** [League-of-Foundry-Developers/fvtt-module-popout#25]
copy of this issue: https://gitlab.com/jesusafier/minimap/-/issues/14

The minimap window does not become a new tab when using the popout module, despite having the option
https://gitlab.com/jesusafier/minimap

Setup:
minimap and popout installed and enabled
minimap active
Expectation:
Clicking popout on the minimap should create a new tab
Result:
The minimap closes briefly before reopening in the FoundryVTT window as before.

**Comment by kakaroto** [comment]
Try 0.9.1. That issue of closing/reopening was not related to minimap, it's your adblocker which closed the popout. It shouldn't happen with 0.9.1 anymore.
The minimap still doesn't work with popout though, as it doesn't seem to recognize clicks.

**Comment by Posnet** [comment]
Hi, I have taken over maintenance of this module. I will look into this issue as soon if it has not been resolved by 0.9.1.

**Comment by Posnet** [comment]
I have tested the latest version of MiniMap with the latest version of PopOut on 0.7.9 and the popout functionality and popin works as expected.

However the actual scrolling does not.

This is due to how the the MiniMap module acquires handles its DOM html elements. It queries for a specific ID from the root document. 
For a module to function with PopOut it must only every acquire handles to DOM elements by querying the actual element of the actual application object, **never** the root `document` or `window`. Please see the following issue for a more in depth discussion https://github.com/League-of-Foundry-Developers/fvtt-module-popout/issues/41
