### ISSUE TITLE
PopOut can't inherit CSS variables applied using hooks in core.

### ISSUE THREAD

**Issue by SalieriC** [League-of-Foundry-Developers/fvtt-module-popout#38]
We are creating a theme module for SWADE called [SWADE Spices & Flavours](https://github.com/SalieriC/SWADE-Spices-Flavours) and were informed of a [compatibility issue](https://github.com/SalieriC/SWADE-Spices-Flavours/issues/34). We use hooks to apply various CSS variables to our stylesheet and thus to the SWADE sheets. Our variables are in the root element of the main window.
From our understanding these variables are not being inherited by the PopOut! window. We cannot create compatibility on our own module and would need PopOut! to either give us hooks we could use or PopOut! needs to inherit the variables set when the sheet is opened in Foundry itself.
Here is a side by side comparison, on the left being Foundry on the right being PopOut!:
![image](https://user-images.githubusercontent.com/1230041/107851568-48341300-6e0b-11eb-9510-d6b09bd8885c.png)
Note that some things we set up inside our .js are used, while the CSS variables we declare in our js and apply them in our stylesheet are not.

**Comment by Posnet** [comment]
Hi, I have taken over maintenance of this module. I will look into this issue as soon.
To be clear, the popout module moves the DOM elements from one window to another, any modifications to the DOM object such as setting CSS style should be persisted. 


Additionally all external CSS should be initialized in the popped out window before the target application is moved. 

Could you please clarify what you mean by root variables? 

If you mean you store variables on the window.xxx object, then that will not work as you have observed. Unfortunately there is no way for me to support arbitrary state attached to the root window object. As long as you are only ever modifying state of child objects of particular application (Where application is the term used by foundry to describe a particular application window). Then popouts should work as expected.

Either way I will try and reproduce your example to find the root cause.

**Comment by javierriveracastro** [comment]
I'll try to explain it. We are using CSS variables here, not javascript variables. They are also named custom properties.

The css variables are created in our css file, assigned default values and attached to :root css element.

This code:

`:root {
	--window-bg-colour: #faf9ed;
	--chat-bg-colour: #ffffff00;`

Afterwards we read the settings that the user has set and modify that variables to match to them (using javascript). 

When the user popouts the sheet the variables values get back to default ones (#faf9ed for window-bg-colour in the example) for the new tab/window. Either because it values doesn't get copied, the css overwrites then or more likely both

As our code runs in the main foundry window it can't touch that values in the popout sheet (or at least I can't figure how to do it).
