### ISSUE TITLE
[Feature] A toggle to hide the words "PopOut!" from the header and add tool tip

### ISSUE THREAD

**Issue by UnoriginalDM** [League-of-Foundry-Developers/fvtt-module-popout#40]
A toggle in the settings to hide the word "PopOut!" in the settings and add a tool tip for the icon.

**Comment by fiagewinnt** [comment]
Can't upvote this enough. Since I'm running Foundry with a lot of modules that also use the header bar, it got kinda overcrowded now and doesn't show the close button anymore. Only when I resize each window manually every time I open a spell/journal entry etc. to accomodate all the symbols. It gets kinda frustrating after a while so it would be great to have an option to preserve space.

Before resizing:
![image](https://user-images.githubusercontent.com/61601634/111866763-17964a80-8970-11eb-92bd-abf88549cde7.png)

After resizing:
![image](https://user-images.githubusercontent.com/61601634/111866774-27ae2a00-8970-11eb-8aae-29e40b42c632.png)

**Comment by kakaroto** [comment]
The close button not appearing is more of a core issue as it should make sure it's always visible. Also, you do have a ton of stuff enabled in there, and you'd have the same issue in the browser anyway. 
Not saying it's not a valid feature request, just saying that Popout being in the header is not your specific problem, it's the fact that you have too many modules enabled that all add buttons and that Foundry core isn't making the close button get priority so it never gets hidden.

**Comment by fiagewinnt** [comment]
> The close button not appearing is more of a core issue as it should make sure it's always visible. Also, you do have a ton of stuff enabled in there, and you'd have the same issue in the browser anyway.
> Not saying it's not a valid feature request, just saying that Popout being in the header is not your specific problem, it's the fact that you have too many modules enabled that all add buttons and that Foundry core isn't making the close button get priority so it never gets hidden.

Thanks for the quick reply. I totally agree with everything you said. Apart from the issues on my side (I scaled back on the header cluttering modules after posting here) I generally like a more minimalistic approach. That's why I'd prefer just a symbol over symbol + text.

I'm going to dig around on the Foundry github if there's already an issue created on the missing close button priority.

**Comment by UnoriginalDM** [comment]
While kakarota is correct, currently, I have not found a way  to fix the issue with foundry core or the 5e system. I have some coding experience but not enough to get me through it.

The quicker, dirter fix I found was to manually remove the header text from my moduIe. It ended up putting the icons closer to each other. Which allowed the close button to show up again.

Fiagwinnt if you find a solution please link it here. Also if you use polyglot or gm notes they have a toggle in the settings.

**Comment by Sekierer** [comment]
I would absolutely adore this change as I run into the same issue as fiagewinnt. But even if it wasn't for having too much other options from different modules I'd really like to see this function. My players are using the Popout module, that's why I have it active but since I'm using the main Foundry application and am not starting it in a browser it's basically "useless" to ME. So a hide option should be definitely added as there will be a lot of DMs who have the same issues. I can't tell you how often I wanted to just drag a window and wondered why it didn't move and I saw the warning message that it doesn't work within the standalone foundry application.

**Comment by Posnet** [comment]
The option to disable the button has been added in the dev branch and should be available in the next release.

**Comment by Posnet** [comment]
I am closing this issue as the main feature will be available in the next release. If there are further requirements around tooltips, please raise as a new issue.
