### ISSUE TITLE
Button on Character Sheet not working with PopOut

### ISSUE THREAD

**Issue by dabeech** [League-of-Foundry-Developers/fvtt-module-popout#41]
System: Low Fantasy Gaming
System Version: 1.1.4
FoundryVTT Version: 0.7.9
PopOut! Version: 1.0

**Issue**
Clicking on the "Luck" button in the Character Sheet does not roll Luck.
Error is logged in Console "_Uncaught TypeError: Cannot read property 'value' of undefined_" pointing to actor-sheet.js line 187.

The button works fine when the Character Sheet is not popped out, both in the browser and in app. The line that the error is pointing to happens to be linked to a dropdown that modifies the Luck roll. All other buttons that send a message to chat seem to work with the PopOut module, though none of them are modified in the same way. This must be an issue with my code, but I thought that I'd reach out in case you might have an idea as to what might be going on. Any help would be appreciated.

**Comment by Posnet** [comment]
The issue is because of this line https://gitlab.com/code382/lfg/-/blob/master/module/actor/actor-sheet.js#L190

Because of how jquery works, using the top level `$` object means it will search the DOM of the main window. Which is a problem because Popout has already moved the element with that html ID to the popped out window, so your event handler will not be able to find the element.

Change it to instead use the actual element from the sheet. i.e. `this.element.find("#luck-modifier")`

In general, it is also worth being careful with html element IDs as they must be globally unique, so if another module also decides that it wants to have an element with `luck-modifier` this will cause problems. I would suggest prefixing all IDs in your module with a known prefix such as `lfg-module-` or something else unlikely to clash. Or you can generate a random prefix and use that instead.

**Comment by kakaroto** [comment]
Hey @Posnet 👋 (Thanks for taking over ❤️!!)

> In general, it is also worth being careful with html element IDs as they must be globally unique, so if another module also decides that it wants to have an element with luck-modifier this will cause problems.

I'm not sure about this luck modifier, but if it's in a character sheet, it means you'll also get problems if you have two character sheets open. The best way to do it in this case would be to use a class and do `this.element.find("input.lfg-module-luck-modifier")` for example.
@dabeech I personally never use ids because I can nearly never guarantee that the element will never appear twice.

**Comment by dabeech** [comment]
Thanks @Posnet and @kakaroto for the help and suggestions! Issue is fixed.
