### ISSUE TITLE
[Help] document eventListeners not available in PoPOut

### ISSUE THREAD

**Issue by sdenec** [League-of-Foundry-Developers/fvtt-module-popout#42]
Hi, I have an issue with tidy5e and the PoPOut module. My sheet uses some document eventListeners and offset/width/height calculations for the sheet. When the sheet gets popped out document and the sheet is no longer available - or reference the original browser window. Is there a way to still have the event listeners and calculations available in the popped out view? Thanks a lot for any information on that :)

**Comment by Posnet** [comment]
Popout relies on being able to move DOM elements between windows. This is a supported, but not regularly used feature of browsers. However it does mean that any event listeners defined on the root of a window or document instead of individual DOM elements will no longer work once a DOM element has been migrated to a new tree.

Could you please show me exactly how you are defining your event listeners? And I can try to offer advice on how to fix them.

The summary will be though that any handle to an Applications HTML elements will have to be via the `app.element` property.
So all calls to `JQuery.find...` or `document.getElement...` must instead use the `app.element` as their root.

**Comment by Posnet** [comment]
@sdenec did my answer help you resolve your issue?

**Comment by sdenec** [comment]
Hi, thanks for your answer. I actually didn't have time to look into it so no progress there ... When I find the time I'll check out your suggestion and see if I am able to implement it.

**Comment by Posnet** [comment]
I have added a more detailed explanation of how PopOut interacts with event listeners to the README and also described the event hooks it provides in detail. Feel free to re-open if you have further questions.
