### ISSUE TITLE
Issue using both HD and UHD screen

### ISSUE THREAD

**Issue by XaaRn** [League-of-Foundry-Developers/fvtt-module-popout#46]
Using both a UHD and HD screens seems to create issue with Popped out windows (Extended Desktop under Windows 10). 

- When the browser is moved from the UHD screen to the extended desktop on the HD screen the resize related to DPI is correct for all windows moved. 
- Any PopOut! window from there will be incorrect (when generated on the HD screen). 
- The initial size/position is incorrect (in part out of screen) potentially due to the initial size/position logic based on the UHD screen where the browser has been opened first and not on the HD screen where the browser now reside/has been moved to. 
- Moving back the browser to the UHD, PopOut! windows generated are again correct.

**Comment by Posnet** [comment]
Could you please provide screenshots of the issue if possible?

**Comment by XaaRn** [comment]
**Test environment:** 
- Laptop w/ UHD + HDMI HD screen
- Windows 10 latest (nothing else)
- Chrome latest
- Foundry 0.7.9
- Latest PopOut!
- New world (world agnostic whatsoever)
- Only PopOut!, 

**Test Steps:**
1. Opening the browser on the UHD screen (default) 
2. Moving the browser to the HD screen
3. Popping out the module management window on the HD screen
4. Moving back the browser to the UHD screen
5. Popping out the module management window on the UHD screen

**Here is the the picture of both:**
![PopOut!-UHDtoHD-DPI-Issue](https://user-images.githubusercontent.com/61934978/116989951-bb467a80-acd2-11eb-9561-390bcff54587.png)

**Comment:**
- Top is the result on the HD screen after step "3."
-  Bottom the same action on the UHD after step "5."
On my extended desktop the screen are also HD top and UHD bottom - hence the popped out windows on the HD screen cannot be grabbed (but through the taskbar)
- Obviously with the deactivation of the "Pop sheets out into windows" , a tab is created with no issue
- The "Bounding box compatibility mode" does not help here

**Comment by Posnet** [comment]
I've been able to reproduce the problem. It appears to be a bug in chrome due to a very specific interaction between chrome windows and window scaling. Specifically, chrome **must** be opened on the first screen with window scaling enabled and it **must** have a higher resolution than the second screen. The second screen **must** have window scaling disabled (i.e. 100%) and have the chrome window moved onto it. I am going to try and put in some fallback code to move the window to a visible location if it detects that it is off screen, but I don't think it will work, in which case there is nothing more I can do. It's a bug in chrome or windows or both.

**Comment by XaaRn** [comment]
> I am going to try and put in some fallback code to move the window to a visible location if it detects that it is off screen

Not perfect maybe, but simply works. Thx a bunch !
