### ISSUE TITLE
Popout Issue with Dice So Nice!

### ISSUE THREAD

**Issue by cckndson** [League-of-Foundry-Developers/fvtt-module-popout#51]
There appears to be a compatibility issue with Popout and Dice So Nice. When rolling for an attack, damage, or any check if Dice So Nice is enabled the popout chat does not update the roll. It will update text or written information. When turning Dice So Nice off functionality is restored and it will see any rolls that are made. 

I tested this with all other modules turned off and slowly turned them on one by one to see when the issue resurfaced and then tested with only Dice So Nice and Popout enabled, the issue persists. 

I'm not sure if this is an issue for Popout or Dice So Nice but wanted to post it and intend to post it for Dice So Nice as well.

**Comment by JiDW** [comment]
Hey, JDW from DsN here, I tried to take a look at the API but I don't think I understand how I could use it.

DsN do this once a roll is over:

```javascript
$(`#chat-log .message[data-message-id="${chatMessage.id}"]`).show();
```

What could we do to make this compatible?

**Comment by Posnet** [comment]
So the issue is that the global jquery object that you get from using the `$` has an implicit reference to the current window. But since the chat has been moved to a difference window, when you try and access something via a selector it will not find it.

Also I am a little surprised that your selector works at all, since the html element ID is meant to be unique within a document, but when you make a local chat popout (not a new window, just right click) it makes a duplicate with the same ID, I guess JQuery just handles it for you.

In terms of actually implementing it so it works, what you will have to do is 2 things.

 1. Instead of calling `$(...)` you should to window.ui.chat.element.find("...selector...")`, this will ensure you are actually accessing the applications html element instead of the global window object. This is true for any DOM access if you want it to work with a popped out window. I'll add this to the readme to try and help other module developers.
 2.  You will **also** have to do the exact same thing but with `window.ui.sidebar.popouts.chat.element.find(...)` . I know this seems crazy to have to do it twice for everything, but that is how it is implemented in foundry.js, every time an action is performed on a sidebar object, it checks if it has a popout, and then applies that action also to the popout. Also, this *only* applies to sidebar tab applications, regular sheets or journals or whatever do not need to do this second step.

**Comment by Posnet** [comment]
In addition I am also considering disabling popout for sidebar items, especially chat, since this is such a serious footgun.

**Comment by JiDW** [comment]
Thanks, it works perfectly!
