### ISSUE TITLE
Conflict with Automated Evocations module

### ISSUE THREAD

**Issue by Dialectikal** [League-of-Foundry-Developers/fvtt-module-popout#56]
With the following turned on, and nothing else:
automated-evocations
libWrapper
PopOut!
Sequencer
Warp Gate

1. Open a character sheet from token
2. Pop out the character sheet
3. Cast a spell with automated-evocations from Spelllist
4. *Companion Manager opens*
5. Drop token from Companion Manager
6. This Succeeds
7. Attempt to cast another spell with automated-evocations from Spelllist
8. The Usage Configuration menu quickly flickers open and closes
9. Can no longer cast spells until character sheet is popped back in

I tried installing PopOut! version 1.1 and did not have this issue.
It only appears to happen with all of the above modules active

**Comment by Posnet** [comment]
I am unable to reproduce the issue. I have followed your instructions using the latest versions of the modules (including PopOut 2.2) you have listed and am able to summon using conjure animals as expected.

Would you please provide the exact versions of every module use are using, as well as a zip of a sample world with an actor setup to reproduce the issue.

**Comment by Posnet** [comment]
Thanks for the details. I think I know what is happening.
I initially saw the issue you were experiencing, however I disabled the PopOut module, to confirm that it was in fact causing the issue and the problem still persisted.
I found that the problem was that the only actors current;y imported from the compendium, were for the `Conjure Animals` spell.
Once I imported ones for other spells, they started appearing as expected.
I.e. I imported a Skeleton and `Animate Dead` started working.

**Comment by Dialectikal** [comment]
Ah, that is normal behavior within AE. The issue I raised was one where the Configuration Menu for ANY spell was no longer appearing. Thankfully, this appears to have been resolved in your latest release: v2.3. I think this issue can be closed :)
