### ISSUE TITLE
Option to disable the buttons label

### ISSUE THREAD

**Issue by SalieriC** [League-of-Foundry-Developers/fvtt-module-popout#59]
An optional setting to disable the "PopOut!" labe, showing only the button as a result.
Veteran players will know the button and will appreciate the saved space which can be crowded with lots of modules anyway.

**Comment by admiralnlson** [comment]
Hello @SalieriC,

I needed the option to hide the label as well because it was causing a display issue with Monarch (module providing a reskin for card hands).
So I implemented the feature and submitted it to ​@Posnet (project maintainer) for approval and inclusion in an upcoming release of PopOut!.

--> https://github.com/League-of-Foundry-Developers/fvtt-module-popout/pull/63

If you're eager to use it, just look at the pull request above. Only 2 files need to be updated. You could do it by hand in your Data/modules/popout/ folder.
Then, to use it, go to module settings from within the FoundryVTT UI and uncheck 'Show PopOut Button label'.
