### ISSUE TITLE
Conflict with Tidy5e Sheet

### ISSUE THREAD

**Issue by Dialectikal** [League-of-Foundry-Developers/fvtt-module-popout#64]
I've discovered a conflict with the Tidy5eSheet module. Whenever I edit an item on the sheet, the item options box stays open after closing the item window. It will do this for up to 3 items usually, before it will close. This only occurs when the character sheet is popped out.

![image](https://user-images.githubusercontent.com/31572084/152443731-d08239d9-3689-40ea-88e9-b1700c0ad98c.png)

The Tidy5eSheet module does have an option to disable the right-click menu, but the problem is still there:
![image](https://user-images.githubusercontent.com/31572084/152443842-a9b8f3f9-b511-4e64-84a4-312bb86c0fe9.png)

**Comment by Posnet** [comment]
I am aware of this issue and have already added a fix for it to the master branch. However I have not yet had a chance to test it to my satisfaction. Sorry for the delay. But the fix will be in the next version.

**Comment by Posnet** [comment]
This issue is not actually fixed. The fix does prevent the creation of more context menus,  however the context menu doesn't close again. This is due to an incompatibility on tidy5e-sheey's side where it assumes there is only ever 1 document in a window. See: https://github.com/sdenec/tidy5e-sheet/blob/master/src/scripts/app/context-menu.js#L89

The fix is either tidy5e-sheet handles more than 1 document by registering itself with all documents, or registering itself with the document from the even it receives rather than the global document object. 
Or it registers itself with the foundry keyboard manager object, which now has compatibility with PopOut as of the next release 2.6.

**Comment by Dialectikal** [comment]
Ok great! Thanks for digging into this. I've updated sdenec with the state of things. Do you happen to know what $(document) should be replaced with, or how to handle registration with those entities?

**Comment by Posnet** [comment]
The [getRootNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode) API will reliably get the correct document element from an arbitrary DOM node, regardless of which window it's in.

**Comment by Dialectikal** [comment]
This appears to have been resolved with the latest update of the Tidy5e Sheet module
