### ISSUE TITLE
.header-button class missing from PopOut header button

### ISSUE THREAD

**Issue by kristianserrano** [League-of-Foundry-Developers/fvtt-module-popout#72]
I noticed the `.header-button` class is missing from the PopOut button in the header. This prevents other modules from styling or otherwise modifying header buttons consistently. Is there a specific reason why it's not present, or is it just an oversight?

**Comment by admiralnlson** [comment]
#65 fixes this already
All that is needed now is PopOut release.

**Comment by Posnet** [comment]
After further testing I have identified that the `header-button` class is reserved by use in the core foundry module and have had to remove it. If you are manually adding that class name to application objects then you will be generating errors due to the fact that foundry expects all elements with that class to have a corresponding event handler registered with the application. 
See line `3202` of `foundry.js` for version 9.255.

**Comment by zeel01** [comment]
This is because as of a few versions ago, Foundry has standardized the method of adding buttons to application headers. The hook:

```js
 Hooks.call(`get${cls.name}HeaderButtons`, this, buttons);
 ```

Called on line `3308` in the `_getHeaderButtons` method. All header buttons should be provided to the buttons object via this hook. Foundry will then appropriately display them, attach their event handlers, etc. 

It appears that a much older method, likely pre-dating hooks, is still being used here involving jQuery. A more substantial refactor will be needed to upgrade the module to utilize the latest API. But the results will be far improved compatibility with other modules.

**Comment by Posnet** [comment]
Thanks for pointing out this new API. It was needed for compatibility with 0.7.  However since I have dropped support for that version I'll consider switching. However there were ordering issues related to relying on hooks that I will need to confirm are no longer a problem.

**Comment by Posnet** [comment]
@zeel01 unfortunately that API actually won't work for the popout use case, since it requires knowing the class name of all windows that might be popped out. I also can't use the windows proxy hack I currently have in place to intercept the buttons array since by that point the window has already been rendered.

**Comment by zeel01** [comment]
You should only need to hook `getApplicationHeaderButtons`, the hook is fired for the entire app inheritance chain.
![image](https://user-images.githubusercontent.com/1721836/157130156-2b9a0edc-e5ed-44d4-8142-5e177761d552.png)

**Comment by Posnet** [comment]
@zeel01 I have done further testing, and it still does not work. "getApplicationHeaderButtons" is never called since `_getInheritanceChain` does to walk to an arbitrary base, it walks until it reaches the defined `baseApplication` property.
