### ISSUE TITLE
Missing Class in Header Button

### ISSUE THREAD

**Issue by mouse0270** [League-of-Foundry-Developers/fvtt-module-popout#88]
Would it be possible to add `class="header-button"` to the header elements

Change this https://github.com/League-of-Foundry-Developers/fvtt-module-popout/blob/14fb495d6c548c6fc6c33d9dce58f5bc5fb01dc6/popout.js#L228-L232
to include the class like below.
```
      const link = $(
        `<a id="${domID}" class="header-button"><i class="fas fa-external-link-alt" title="${game.i18n.localize(
          "POPOUT.PopOut"
        )}"></i>${buttonText}</a>`
      );
```

**Comment by Posnet** [comment]
I am currently traveling without a dev laptop, I'll take a look at this when I can, probably early November.

**Comment by mouse0270** [comment]
It's just a consistent update. no rush.

**Comment by admiralnlson** [comment]
Similar suggestion as I made in issue #72 and my PR #65 back in March.

@Posnet at the time, you said you analysed Core code and concluded add the class would be causing core errors. But I can confirm that what @mouse0270 suggests above, which I've used for months now, does not lead to errors in practice.

**Comment by Posnet** [comment]
I have tested it again, and it still produces errors. Please see line 5195 of `foundry.js`.

```js
    // Activate header button click listeners after a slight timeout to prevent immediate interaction
    setTimeout(() => {
      html.find(".header-button").click(event => {
        event.preventDefault();
        const button = windowData.headerButtons.find(b => event.currentTarget.classList.contains(b.class));
        button.onclick(event);
      });
    }, 500);
```

The popout button is **not** in the windowData.headerButtons list because it wasn't added to it via the normal `get{cls.name}HeaderButtons` hook.

I have tried to get popout working using this official method of adding header buttons, however the `getInheritanceChain` method does not walk to the top level Application class. In order to support all possible application window objects I have to interpose the ui.windows collection instead. It is the only current reliable way I've found to have popout handler code be called on every application window create event.

I am open to suggestions as to a better method, however I will not break backwards compatibility, so any new method must support all application windows, and must work on v9 until v11 is released.

**Comment by mouse0270** [comment]
I don't care where you add it, I just want it to have the class so it receives proper styling when someone changes how that class looks. Also so its can be targeted via CSS query statements without special coding... IT IS A HEADER BUTTON, it should have the class `header-button`

**Comment by mouse0270** [comment]
I'd be happy if you gave it any class so it could be targeted via CSS... Right now there is nothing to target it. Its just a random anchor tag with no indication of what it is.

**Comment by Posnet** [comment]
that is reasonable, I'll add a class to the anchor node.

**Comment by Posnet** [comment]
there is now a `popout-module-button` css class on the popout link.
